# Generated by Django 5.1 on 2024-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=80, verbose_name="Название фильма"),
                ),
                (
                    "synopsis",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Синопсис"
                    ),
                ),
                ("review", models.TextField(verbose_name="Отзыв")),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Опубликовано"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
